### ISSUE TITLE
People Picker Disabled doesn't work

### ISSUE THREAD

**Issue by enti333** [pnp/sp-dev-fx-controls-react#484]
[ ] Enhancement
[X] Bug
[ ] Question

Hello. I don't know why but when I use people picker control and set the property disabled to true I am still able to click on X icon a remove users from people picker....
It happen in all version of pnp react. 

Hmm... Thank you for your help.

**Comment by AJIXuMuK** [comment]
Hi @enti333,
This is a known issue of underlying Office UI Fabric React control. [Here](https://github.com/OfficeDev/office-ui-fabric-react/issues/7596) is the description.
It has been fixed in version 6.129.0. 
We have plans on upgrading used version of OUIFR. After that the issue will be fixed.

**Comment by fonbrauzen** [comment]
Hi, @AJIXuMuK do you have any estimations, when the update to OUIFR v6.129.0+ could happen?

**Comment by Steven-Chorkawy** [comment]
Hello, 

I've also run into this bug. 
Has there been any update on it?

**Comment by AJIXuMuK** [comment]
Hi all,

There is already [v2 beta version](https://www.npmjs.com/package/@pnp/spfx-controls-react/v/2.0.0-beta.8fc2462).

We plan to release it next week.

**Comment by holylander** [comment]
I still see this issue on going. The picker will be disabled, but if there is any user already setup on the control, any will be able to delete such record

**Comment by jduysen** [comment]
For anyone finding this in 2023 who is still using older versions of these libraries because of being on Sharepoint 2019, I resolved this with a workaround in my dynamic form component.  Essentially just surrounded the people picker with a div with a conditional style for pointer events.  This effectively disables the people picker so the name cannot be removed if the people picker is supposed to be disabled.
Example:
`<div style={this.props.disabled?{"pointerEvents": "none"}:{}}><PeoplePicker/><div>`

**Comment by NMarkovic98** [comment]
> For anyone finding this in 2023 who is still using older versions of these libraries because of being on Sharepoint 2019, I resolved this with a workaround in my dynamic form component. Essentially just surrounded the people picker with a div with a conditional style for pointer events. This effectively disables the people picker so the name cannot be removed if the people picker is supposed to be disabled. Example: `<div style={this.props.disabled?{"pointerEvents": "none"}:{}}><PeoplePicker/><div>`

Thanks! You saved me hours of researching!

**Comment by jduysen** [comment]
@NMarkovic98, glad it helped!
