### ISSUE TITLE
PnP SPFx DateTimePicker Clear Date functionality

### ISSUE THREAD

**Issue by dineshtalekar777** [pnp/sp-dev-fx-controls-react#799]
As a end I don't have feasibility to clear the selected date with the PnP SPFx DateTimePicker control. Could some one please help on this if this is already fixed

**Comment by AJIXuMuK** [comment]
Hi @dineshtalekar777,
Thank you for reporting this one!

The fix has been merged and will be included in the next release.

In a meanwhile you can test the functionality in [beta version](https://pnp.github.io/sp-dev-fx-controls-react/beta/).

**Comment by AJIXuMuK** [comment]
`v2.5.0` has been released.

**Comment by lexschulz** [comment]
Hi Alex, 

I upgraded my version of spfx-controls-react to 2.7.0 but it's not possible to clear the date.
I am not sure what to do now. Greetings

> `v2.5.0` has been released.

**Comment by AJIXuMuK** [comment]
@lexschulz  - how are you clearing the date?

**Comment by lexschulz** [comment]
> @lexschulz - how are you clearing the date?

Hi Alex,
I can only select a date or click "Today" but there is no way to delete the value that's in the field so that it's an empty field again.
I thought that I can mark and delete the date ... or can select "Delete" like the "Go to today" link... but after upgrading from 2.3.0 to 2.7.0 it's still not possible.
The onchange event only triggers when I select a date, so I have no idea how to clear an existing date. Thanks for your response!
